### ISSUE TITLE
configure is not imported from @beyonk/sapper-httpclient

### ISSUE THREAD

**Issue by sharmapukar112** [beyonk-adventures/sapper-httpclient#5]
when doing import { configure } from "@beyonk/sapper-httpclient" in server.js, the configure module is imported but while doing the same in client.js, it shows Non-existent export 'configure' is imported from node_modules/@beyonk/sapper-httpclient/index.js

**Comment by antony** [comment]
Not sure why that would be the case, but I use:

```
import Api from '@beyonk/sapper-httpclient'

Api.configure({
  baseUrl: process.env.apiUrl
})
```
