### ISSUE TITLE
'fetch' is not exported by @sapper/app

### ISSUE THREAD

**Issue by ashwinvasudevan** [beyonk-adventures/sapper-httpclient#9]
In your Isomorphic example, I am unable to import fetch from @sapper/app
I am running Svelte 3.24
```
<script context="module">
  import { create } from "@beyonk/sapper-httpclient";
  import { fetch } from "@sapper/app";

  export async function preload(page, session) {
    const api = create();
    const res = await api
      .transport(fetch) // Use sapper's built in "fetch" method
      .endpoint("http://scrapex.local/api/")
      .get();
  }
</script>
```
Also, how can I add 'credentials': 'include' with this isomorphic fetch call?

**Comment by antony** [comment]
Credentials include is the default.

The reason you can't find `fetch` in `@sapper/app` is because it doesn't exist there (oops, sorry!). The fetch method in a module script context is `this.fetch`. I'll update the readme!
